spring:
  application:
    name: Zuul

server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-s:
      path: /api/s/**
      serviceId: Service-Books
    api-w:
      path: /api/w/**
      serviceId: Web-Books
